/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardAtom: typeof import('./src/components/CardAtom/CardAtom.vue')['default']
    CardGroup: typeof import('./src/components/CardGroup/CardGroup.vue')['default']
    CommonEmptyState: typeof import('./src/components/CommonEmptyState/CommonEmptyState.vue')['default']
    CommonSectionCard: typeof import('./src/components/CommonSectionCard/CommonSectionCard.vue')['default']
    ConfettiOverlay: typeof import('./src/components/ConfettiOverlay/ConfettiOverlay.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ProjectMetaDialog: typeof import('./src/components/ProjectMetaDialog/ProjectMetaDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextEllipsis: typeof import('./src/components/TextEllipsis/TextEllipsis.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const CardAtom: typeof import('./src/components/CardAtom/CardAtom.vue')['default']
  const CardGroup: typeof import('./src/components/CardGroup/CardGroup.vue')['default']
  const CommonEmptyState: typeof import('./src/components/CommonEmptyState/CommonEmptyState.vue')['default']
  const CommonSectionCard: typeof import('./src/components/CommonSectionCard/CommonSectionCard.vue')['default']
  const ConfettiOverlay: typeof import('./src/components/ConfettiOverlay/ConfettiOverlay.vue')['default']
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ProjectMetaDialog: typeof import('./src/components/ProjectMetaDialog/ProjectMetaDialog.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TextEllipsis: typeof import('./src/components/TextEllipsis/TextEllipsis.vue')['default']
}